name: Monitoramento Jira

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas psutil boto3 requests

    - name: Rodar Script de Monitoramento
      env:
        EMAIL_JIRA: ${{ secrets.EMAIL_JIRA }}
        TOKEN_JIRA: ${{ secrets.TOKEN_JIRA }}
        
      run: |
        # üö® DEBUG: Verifica se as vari√°veis foram carregadas antes de rodar o Python
        echo "Verificando vari√°veis de ambiente antes da execu√ß√£o:"
        echo "EMAIL_JIRA: ${EMAIL_JIRA:+SIM} (Injetado)" || echo "EMAIL_JIRA: NAO (Vazio)"
        echo "TOKEN_JIRA: ${TOKEN_JIRA:+SIM} (Injetado)" || echo "TOKEN_JIRA: NAO (Vazio)"
        
        # Comando para rodar o script
        python monitoramento.py